name: Deploy Supabase Edge Functions

on:
  push:
    paths:
      - 'supabase/functions/**'
      - 'supabase/config.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Login to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_CLI_TOKEN }}
        run: supabase login --token $SUPABASE_ACCESS_TOKEN

      - name: Deploy functions
        run: supabase functions deploy stream --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
